#!/usr/bin/env python3
"""generateSymbolicMaps.py

Generate COBOL BMS *symbolic map* copybooks from the CBSA ``.bms`` mapset
sources for the isolated-test harness.

On z/OS the symbolic map copybooks (the ``01 <map>I`` / ``01 <map>O``
structures a program COPYs) are produced by assembling the ``.bms`` with
``TYPE=DSECT``. Off-CICS we do not have the BMS macro assembler, so this
script performs the same job for the subset of BMS these CBSA presentation
programs use: it reads a mapset, and for every *named* ``DFHMDF`` field it
emits the classic symbolic-map fields.

For each named field ``NAME`` of screen length ``len`` the input map gets::

    02  NAMEL  PIC S9(4) COMP.      <- field length / cursor (-1)
    02  NAMEF  PIC X.               <- input flag / attribute
    02  FILLER REDEFINES NAMEF.
        03 NAMEA PIC X.
    02  NAMEI  PIC X(len).          <- input data

and the redefining output map gets::

    02  FILLER PIC X(3).            <- over L + F/A
    02  NAMEO  PIC X(len).          <- output data (or PICOUT edit picture)

Both groups start with the 12-byte ``FILLER`` produced by ``TIOAPFX=YES``.

The extended-attribute symbolic bytes (COLOR/HILIGHT/PS/... from
``MAPATTS``/``DSATTS``) are intentionally omitted: none of the programs
under test reference them, and because the driver and the program share
*this* generated copybook the only requirement is internal consistency,
not byte-for-byte parity with the mainframe generator.

Usage:
    python3 generateSymbolicMaps.py <mapset.bms> [more.bms ...] --outDir DIR

The output copybook is named ``<MAPSET>.cpy`` (the ``DFHMSD`` label), which
is what the programs COPY.
"""

import argparse
import os
import re
import sys

# Fixed-format continuation indicator lives in column 72 (1-based); the
# operand area of a continued line resumes at column 16 (1-based).
CONT_COL = 72
RESUME_COL = 16


def _logicalLines(text):
    """Collapse BMS physical lines (with col-72 continuations) into logical
    statements, dropping full-line comments (``*`` in column 1)."""
    logical = []
    current = None
    for physical in text.split("\n"):
        if not physical.strip():
            continue
        if physical[0] in ("*",):
            continue
        continued = len(physical) >= CONT_COL and physical[CONT_COL - 1] not in (" ",)
        body = physical[:CONT_COL - 1]
        if current is None:
            current = body.rstrip()
        else:
            current += body[RESUME_COL - 1:].strip()
        if not continued:
            logical.append(current)
            current = None
    if current is not None:
        logical.append(current)
    return logical


def _field(logical):
    """Return ``(name, length, picout)`` for a named ``DFHMDF`` logical line,
    or ``None`` for an unnamed (literal) field or a non-DFHMDF line."""
    tokens = logical.split()
    if len(tokens) < 2 or tokens[1] != "DFHMDF":
        return None  # unnamed field (starts with DFHMDF) or not a field
    name = tokens[0]
    lenMatch = re.search(r"LENGTH=(\d+)", logical)
    if not lenMatch:
        raise ValueError("DFHMDF {} has no LENGTH=".format(name))
    length = int(lenMatch.group(1))
    if re.search(r"\bOCCURS=", logical) or re.search(r"\bGRPNAME=", logical):
        raise NotImplementedError(
            "field {} uses OCCURS/GRPNAME which the generator does not "
            "support".format(name))
    picoutMatch = re.search(r"PICOUT='([^']*)'", logical)
    picout = picoutMatch.group(1) if picoutMatch else None
    return name, length, picout


def parseMapset(text):
    """Parse a mapset ``.bms`` -> ``(mapsetName, mapName, [fields])``."""
    mapset = None
    mapName = None
    fields = []
    for logical in _logicalLines(text):
        tokens = logical.split()
        if len(tokens) >= 2 and tokens[1] == "DFHMSD":
            mapset = tokens[0]
        elif len(tokens) >= 2 and tokens[1] == "DFHMDI":
            mapName = tokens[0]
        elif "DFHMDF" in logical:
            parsed = _field(logical)
            if parsed is not None:
                fields.append(parsed)
    if not mapset or not mapName:
        raise ValueError("could not find DFHMSD/DFHMDI in mapset")
    return mapset, mapName, fields


def _pic(length):
    return "PIC X({})".format(length)


def renderCopybook(mapset, mapName, fields, sourceName):
    lines = []
    lines.append("      ******************************************************************")
    lines.append("      * {}.cpy - BMS symbolic map (harness generated).".format(mapset))
    lines.append("      *")
    lines.append("      * Generated by tests/harness/generateSymbolicMaps.py from")
    lines.append("      * {}. DO NOT EDIT BY HAND.".format(sourceName))
    lines.append("      ******************************************************************")
    # Input map.
    lines.append("       01  {}I.".format(mapName))
    lines.append("           02  FILLER PIC X(12).")
    for name, length, _ in fields:
        lines.append("           02  {}L  PIC S9(4) COMP.".format(name))
        lines.append("           02  {}F  PIC X.".format(name))
        lines.append("           02  FILLER REDEFINES {}F.".format(name))
        lines.append("               03  {}A  PIC X.".format(name))
        lines.append("           02  {}I  {}.".format(name, _pic(length)))
    # Output map (redefinition).
    lines.append("       01  {}O REDEFINES {}I.".format(mapName, mapName))
    lines.append("           02  FILLER PIC X(12).")
    for name, length, picout in fields:
        lines.append("           02  FILLER PIC X(3).")
        if picout:
            lines.append("           02  {}O  PIC {}.".format(name, picout))
        else:
            lines.append("           02  {}O  {}.".format(name, _pic(length)))
    return "\n".join(lines) + "\n"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sources", nargs="+", help="mapset .bms files")
    ap.add_argument("--outDir", required=True, help="output directory for .cpy")
    args = ap.parse_args(argv[1:])

    os.makedirs(args.outDir, exist_ok=True)
    for src in args.sources:
        with open(src, "r") as fh:
            text = fh.read()
        mapset, mapName, fields = parseMapset(text)
        copybook = renderCopybook(mapset, mapName, fields, os.path.basename(src))
        outPath = os.path.join(args.outDir, "{}.cpy".format(mapset))
        with open(outPath, "w") as fh:
            fh.write(copybook)
        sys.stderr.write("generated {} ({} fields) from {}\n".format(
            outPath, len(fields), os.path.basename(src)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
