      ******************************************************************
      * BNK1CAM.cpy - BMS symbolic map (harness generated).
      *
      * Generated by tests/harness/generateSymbolicMaps.py from
      * BNK1CAM.bms. DO NOT EDIT BY HAND.
      ******************************************************************
       01  BNK1CAI.
           02  FILLER PIC X(12).
           02  COMPANYL  PIC S9(4) COMP.
           02  COMPANYF  PIC X.
           02  FILLER REDEFINES COMPANYF.
               03  COMPANYA  PIC X.
           02  COMPANYI  PIC X(61).
           02  CUSTNOL  PIC S9(4) COMP.
           02  CUSTNOF  PIC X.
           02  FILLER REDEFINES CUSTNOF.
               03  CUSTNOA  PIC X.
           02  CUSTNOI  PIC X(10).
           02  ACCTYPL  PIC S9(4) COMP.
           02  ACCTYPF  PIC X.
           02  FILLER REDEFINES ACCTYPF.
               03  ACCTYPA  PIC X.
           02  ACCTYPI  PIC X(8).
           02  INTRTL  PIC S9(4) COMP.
           02  INTRTF  PIC X.
           02  FILLER REDEFINES INTRTF.
               03  INTRTA  PIC X.
           02  INTRTI  PIC X(7).
           02  OVERDRL  PIC S9(4) COMP.
           02  OVERDRF  PIC X.
           02  FILLER REDEFINES OVERDRF.
               03  OVERDRA  PIC X.
           02  OVERDRI  PIC X(8).
           02  ACCNOL  PIC S9(4) COMP.
           02  ACCNOF  PIC X.
           02  FILLER REDEFINES ACCNOF.
               03  ACCNOA  PIC X.
           02  ACCNOI  PIC X(8).
           02  SRTCDL  PIC S9(4) COMP.
           02  SRTCDF  PIC X.
           02  FILLER REDEFINES SRTCDF.
               03  SRTCDA  PIC X.
           02  SRTCDI  PIC X(6).
           02  OPENDDL  PIC S9(4) COMP.
           02  OPENDDF  PIC X.
           02  FILLER REDEFINES OPENDDF.
               03  OPENDDA  PIC X.
           02  OPENDDI  PIC X(2).
           02  OPENMML  PIC S9(4) COMP.
           02  OPENMMF  PIC X.
           02  FILLER REDEFINES OPENMMF.
               03  OPENMMA  PIC X.
           02  OPENMMI  PIC X(2).
           02  OPENYYL  PIC S9(4) COMP.
           02  OPENYYF  PIC X.
           02  FILLER REDEFINES OPENYYF.
               03  OPENYYA  PIC X.
           02  OPENYYI  PIC X(4).
           02  LSTMDDL  PIC S9(4) COMP.
           02  LSTMDDF  PIC X.
           02  FILLER REDEFINES LSTMDDF.
               03  LSTMDDA  PIC X.
           02  LSTMDDI  PIC X(2).
           02  LSTMMML  PIC S9(4) COMP.
           02  LSTMMMF  PIC X.
           02  FILLER REDEFINES LSTMMMF.
               03  LSTMMMA  PIC X.
           02  LSTMMMI  PIC X(2).
           02  LSTMYYL  PIC S9(4) COMP.
           02  LSTMYYF  PIC X.
           02  FILLER REDEFINES LSTMYYF.
               03  LSTMYYA  PIC X.
           02  LSTMYYI  PIC X(4).
           02  NSTMTDDL  PIC S9(4) COMP.
           02  NSTMTDDF  PIC X.
           02  FILLER REDEFINES NSTMTDDF.
               03  NSTMTDDA  PIC X.
           02  NSTMTDDI  PIC X(2).
           02  NSTMTMML  PIC S9(4) COMP.
           02  NSTMTMMF  PIC X.
           02  FILLER REDEFINES NSTMTMMF.
               03  NSTMTMMA  PIC X.
           02  NSTMTMMI  PIC X(2).
           02  NSTMTYYL  PIC S9(4) COMP.
           02  NSTMTYYF  PIC X.
           02  FILLER REDEFINES NSTMTYYF.
               03  NSTMTYYA  PIC X.
           02  NSTMTYYI  PIC X(4).
           02  AVAILL  PIC S9(4) COMP.
           02  AVAILF  PIC X.
           02  FILLER REDEFINES AVAILF.
               03  AVAILA  PIC X.
           02  AVAILI  PIC X(14).
           02  ACTBALL  PIC S9(4) COMP.
           02  ACTBALF  PIC X.
           02  FILLER REDEFINES ACTBALF.
               03  ACTBALA  PIC X.
           02  ACTBALI  PIC X(14).
           02  MESSAGEL  PIC S9(4) COMP.
           02  MESSAGEF  PIC X.
           02  FILLER REDEFINES MESSAGEF.
               03  MESSAGEA  PIC X.
           02  MESSAGEI  PIC X(79).
           02  DUMMYL  PIC S9(4) COMP.
           02  DUMMYF  PIC X.
           02  FILLER REDEFINES DUMMYF.
               03  DUMMYA  PIC X.
           02  DUMMYI  PIC X(1).
       01  BNK1CAO REDEFINES BNK1CAI.
           02  FILLER PIC X(12).
           02  FILLER PIC X(3).
           02  COMPANYO  PIC X(61).
           02  FILLER PIC X(3).
           02  CUSTNOO  PIC X(10).
           02  FILLER PIC X(3).
           02  ACCTYPO  PIC X(8).
           02  FILLER PIC X(3).
           02  INTRTO  PIC X(7).
           02  FILLER PIC X(3).
           02  OVERDRO  PIC X(8).
           02  FILLER PIC X(3).
           02  ACCNOO  PIC X(8).
           02  FILLER PIC X(3).
           02  SRTCDO  PIC X(6).
           02  FILLER PIC X(3).
           02  OPENDDO  PIC X(2).
           02  FILLER PIC X(3).
           02  OPENMMO  PIC X(2).
           02  FILLER PIC X(3).
           02  OPENYYO  PIC X(4).
           02  FILLER PIC X(3).
           02  LSTMDDO  PIC X(2).
           02  FILLER PIC X(3).
           02  LSTMMMO  PIC X(2).
           02  FILLER PIC X(3).
           02  LSTMYYO  PIC X(4).
           02  FILLER PIC X(3).
           02  NSTMTDDO  PIC X(2).
           02  FILLER PIC X(3).
           02  NSTMTMMO  PIC X(2).
           02  FILLER PIC X(3).
           02  NSTMTYYO  PIC X(4).
           02  FILLER PIC X(3).
           02  AVAILO  PIC X(14).
           02  FILLER PIC X(3).
           02  ACTBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  MESSAGEO  PIC X(79).
           02  FILLER PIC X(3).
           02  DUMMYO  PIC X(1).
