      ******************************************************************
      * BNK1TFM.cpy - BMS symbolic map (harness generated).
      *
      * Generated by tests/harness/generateSymbolicMaps.py from
      * BNK1TFM.bms. DO NOT EDIT BY HAND.
      ******************************************************************
       01  BNK1TFI.
           02  FILLER PIC X(12).
           02  COMPANYL  PIC S9(4) COMP.
           02  COMPANYF  PIC X.
           02  FILLER REDEFINES COMPANYF.
               03  COMPANYA  PIC X.
           02  COMPANYI  PIC X(61).
           02  FACCNOL  PIC S9(4) COMP.
           02  FACCNOF  PIC X.
           02  FILLER REDEFINES FACCNOF.
               03  FACCNOA  PIC X.
           02  FACCNOI  PIC X(8).
           02  TACCNOL  PIC S9(4) COMP.
           02  TACCNOF  PIC X.
           02  FILLER REDEFINES TACCNOF.
               03  TACCNOA  PIC X.
           02  TACCNOI  PIC X(8).
           02  AMTL  PIC S9(4) COMP.
           02  AMTF  PIC X.
           02  FILLER REDEFINES AMTF.
               03  AMTA  PIC X.
           02  AMTI  PIC X(13).
           02  FACCNO2L  PIC S9(4) COMP.
           02  FACCNO2F  PIC X.
           02  FILLER REDEFINES FACCNO2F.
               03  FACCNO2A  PIC X.
           02  FACCNO2I  PIC X(8).
           02  TACCNO2L  PIC S9(4) COMP.
           02  TACCNO2F  PIC X.
           02  FILLER REDEFINES TACCNO2F.
               03  TACCNO2A  PIC X.
           02  TACCNO2I  PIC X(8).
           02  FSORTCL  PIC S9(4) COMP.
           02  FSORTCF  PIC X.
           02  FILLER REDEFINES FSORTCF.
               03  FSORTCA  PIC X.
           02  FSORTCI  PIC X(6).
           02  TSORTCL  PIC S9(4) COMP.
           02  TSORTCF  PIC X.
           02  FILLER REDEFINES TSORTCF.
               03  TSORTCA  PIC X.
           02  TSORTCI  PIC X(6).
           02  FACTBALL  PIC S9(4) COMP.
           02  FACTBALF  PIC X.
           02  FILLER REDEFINES FACTBALF.
               03  FACTBALA  PIC X.
           02  FACTBALI  PIC X(14).
           02  TACTBALL  PIC S9(4) COMP.
           02  TACTBALF  PIC X.
           02  FILLER REDEFINES TACTBALF.
               03  TACTBALA  PIC X.
           02  TACTBALI  PIC X(14).
           02  FAVBALL  PIC S9(4) COMP.
           02  FAVBALF  PIC X.
           02  FILLER REDEFINES FAVBALF.
               03  FAVBALA  PIC X.
           02  FAVBALI  PIC X(14).
           02  TAVBALL  PIC S9(4) COMP.
           02  TAVBALF  PIC X.
           02  FILLER REDEFINES TAVBALF.
               03  TAVBALA  PIC X.
           02  TAVBALI  PIC X(14).
           02  MESSAGEL  PIC S9(4) COMP.
           02  MESSAGEF  PIC X.
           02  FILLER REDEFINES MESSAGEF.
               03  MESSAGEA  PIC X.
           02  MESSAGEI  PIC X(79).
           02  DUMMYL  PIC S9(4) COMP.
           02  DUMMYF  PIC X.
           02  FILLER REDEFINES DUMMYF.
               03  DUMMYA  PIC X.
           02  DUMMYI  PIC X(1).
       01  BNK1TFO REDEFINES BNK1TFI.
           02  FILLER PIC X(12).
           02  FILLER PIC X(3).
           02  COMPANYO  PIC X(61).
           02  FILLER PIC X(3).
           02  FACCNOO  PIC X(8).
           02  FILLER PIC X(3).
           02  TACCNOO  PIC X(8).
           02  FILLER PIC X(3).
           02  AMTO  PIC X(13).
           02  FILLER PIC X(3).
           02  FACCNO2O  PIC X(8).
           02  FILLER PIC X(3).
           02  TACCNO2O  PIC X(8).
           02  FILLER PIC X(3).
           02  FSORTCO  PIC X(6).
           02  FILLER PIC X(3).
           02  TSORTCO  PIC X(6).
           02  FILLER PIC X(3).
           02  FACTBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  TACTBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  FAVBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  TAVBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  MESSAGEO  PIC X(79).
           02  FILLER PIC X(3).
           02  DUMMYO  PIC X(1).
