      ******************************************************************
      * BNK1CDM.cpy - BMS symbolic map (harness generated).
      *
      * Generated by tests/harness/generateSymbolicMaps.py from
      * BNK1CDM.bms. DO NOT EDIT BY HAND.
      ******************************************************************
       01  BNK1CDI.
           02  FILLER PIC X(12).
           02  COMPANYL  PIC S9(4) COMP.
           02  COMPANYF  PIC X.
           02  FILLER REDEFINES COMPANYF.
               03  COMPANYA  PIC X.
           02  COMPANYI  PIC X(61).
           02  ACCNOL  PIC S9(4) COMP.
           02  ACCNOF  PIC X.
           02  FILLER REDEFINES ACCNOF.
               03  ACCNOA  PIC X.
           02  ACCNOI  PIC X(8).
           02  SIGNL  PIC S9(4) COMP.
           02  SIGNF  PIC X.
           02  FILLER REDEFINES SIGNF.
               03  SIGNA  PIC X.
           02  SIGNI  PIC X(1).
           02  AMTL  PIC S9(4) COMP.
           02  AMTF  PIC X.
           02  FILLER REDEFINES AMTF.
               03  AMTA  PIC X.
           02  AMTI  PIC X(13).
           02  SORTCL  PIC S9(4) COMP.
           02  SORTCF  PIC X.
           02  FILLER REDEFINES SORTCF.
               03  SORTCA  PIC X.
           02  SORTCI  PIC X(6).
           02  AVBALL  PIC S9(4) COMP.
           02  AVBALF  PIC X.
           02  FILLER REDEFINES AVBALF.
               03  AVBALA  PIC X.
           02  AVBALI  PIC X(14).
           02  ACTBALL  PIC S9(4) COMP.
           02  ACTBALF  PIC X.
           02  FILLER REDEFINES ACTBALF.
               03  ACTBALA  PIC X.
           02  ACTBALI  PIC X(14).
           02  MESSAGEL  PIC S9(4) COMP.
           02  MESSAGEF  PIC X.
           02  FILLER REDEFINES MESSAGEF.
               03  MESSAGEA  PIC X.
           02  MESSAGEI  PIC X(79).
           02  DUMMYL  PIC S9(4) COMP.
           02  DUMMYF  PIC X.
           02  FILLER REDEFINES DUMMYF.
               03  DUMMYA  PIC X.
           02  DUMMYI  PIC X(1).
       01  BNK1CDO REDEFINES BNK1CDI.
           02  FILLER PIC X(12).
           02  FILLER PIC X(3).
           02  COMPANYO  PIC X(61).
           02  FILLER PIC X(3).
           02  ACCNOO  PIC X(8).
           02  FILLER PIC X(3).
           02  SIGNO  PIC X(1).
           02  FILLER PIC X(3).
           02  AMTO  PIC X(13).
           02  FILLER PIC X(3).
           02  SORTCO  PIC X(6).
           02  FILLER PIC X(3).
           02  AVBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  ACTBALO  PIC X(14).
           02  FILLER PIC X(3).
           02  MESSAGEO  PIC X(79).
           02  FILLER PIC X(3).
           02  DUMMYO  PIC X(1).
