      ******************************************************************
      * BNK1MAI.cpy - BMS symbolic map (harness generated).
      *
      * Generated by tests/harness/generateSymbolicMaps.py from
      * BNK1MAI.bms. DO NOT EDIT BY HAND.
      ******************************************************************
       01  BNK1MEI.
           02  FILLER PIC X(12).
           02  COMPANYL  PIC S9(4) COMP.
           02  COMPANYF  PIC X.
           02  FILLER REDEFINES COMPANYF.
               03  COMPANYA  PIC X.
           02  COMPANYI  PIC X(43).
           02  ACTIONL  PIC S9(4) COMP.
           02  ACTIONF  PIC X.
           02  FILLER REDEFINES ACTIONF.
               03  ACTIONA  PIC X.
           02  ACTIONI  PIC X(1).
           02  MESSAGEL  PIC S9(4) COMP.
           02  MESSAGEF  PIC X.
           02  FILLER REDEFINES MESSAGEF.
               03  MESSAGEA  PIC X.
           02  MESSAGEI  PIC X(79).
           02  DUMMYL  PIC S9(4) COMP.
           02  DUMMYF  PIC X.
           02  FILLER REDEFINES DUMMYF.
               03  DUMMYA  PIC X.
           02  DUMMYI  PIC X(1).
       01  BNK1MEO REDEFINES BNK1MEI.
           02  FILLER PIC X(12).
           02  FILLER PIC X(3).
           02  COMPANYO  PIC X(43).
           02  FILLER PIC X(3).
           02  ACTIONO  PIC X(1).
           02  FILLER PIC X(3).
           02  MESSAGEO  PIC X(79).
           02  FILLER PIC X(3).
           02  DUMMYO  PIC X(1).
